metadata.format.version = "1.1"

[versions]

# Compile only
velocity = "3.4.0-SNAPSHOT"
bstats = "3.1.0"

blossom = "2.1.0"
runvelocity = "2.3.1"
shadow = "9.0.0-beta10"

packetevents = "2.7.0"

[libraries]

# Compile Only Dependencies
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
velocity-proxy = { group = "com.velocitypowered", name = "velocity-proxy", version.ref = "velocity" }
# Included dependencies
bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }
packetevents = { group = "com.github.retrooper", name = "packetevents-velocity", version.ref = "packetevents" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
